force-app/main/default/objects/ht_Insurance_Product_LOA_Mapping__c/ht_Insurance_Product_LOA_Mapping__c.object-meta.xml
<CustomObject>
    <label>NIPR Insurance Product LOA Mapping</label>
    <nameField>
        <displayFormat>IPLM-{0000}</displayFormat>
        <label>Mapping Product Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Insurance Product LOA Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ht_Insurance_Product_LOA_Mapping__c/fields/ht_LOAMapping__c.field-meta.xml
<CustomField>
    <fullName>ht_LOAMapping__c</fullName>
    <label>LOA Mapping</label>
    <referenceTo>ht_LOA_Insurance_Product_Mapping__c</referenceTo>
    <relationshipLabel>LOA Mapping Insurance Products</relationshipLabel>
    <relationshipName>LOA_Mapping_Insurance_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ht_LOA_Insurance_Product_Mapping__c/fields/ht_LineOfAuthorityCode__c.field-meta.xml
<CustomField>
    <fullName>ht_LineOfAuthorityCode__c</fullName>
    <label>Line Of Authority Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ht_LOA_Insurance_Product_Mapping__c/fields/ht_StateOrProvinceCode__c.field-meta.xml
<CustomField>
    <fullName>d4c_StateOrProvinceCode__c</fullName>
    <label>State Or Province Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ht_LOA_Insurance_Product_Mapping__c/fields/ht_UniqueIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ht_UniqueIdentifier__c</fullName>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Repository/LOAInsuranceProductMappingSelector.cls
/*
*********************************************************
Apex Class Name    : LOAInsuranceProductMappingSelector
Created Date       : 2025-12-15
@description       : Selector class for querying ht_LOA_Insurance_Product_Mapping__c records
@author            : Stefan Nidzovic
Modification Log:
Ver   Date         Author         Modification
1.0   2025-12-15   Stefan Nidzovic         Initial Version
*********************************************************
*/
public with sharing class LOAInsuranceProductMappingSelector {

    /**
     ********************************************************
     * @Method Name    : getMappingsByIds
     * @description    : Returns list of LOA Insurance Product Mappings by Id
     * @param          : mappingIds - Set of LOA Mapping IDs
     * @return         : List<ht_LOA_Insurance_Product_Mapping__c> - list of LOA Mapping records
     *******************************************************
     **/
    public List<ht_LOA_Insurance_Product_Mapping__c> getMappingsByIds(Set<Id> mappingIds) {
        return [
            SELECT
                Id,
                ht_StateOrProvinceCode__c,
                ht_LineOfAuthorityCode__c,
                ht_LineOfAuthorityDescription__c,
                ht_UniqueIdentifier__c
            FROM
                ht_LOA_Insurance_Product_Mapping__c
            WHERE
                Id IN :mappingIds
        ];
    }

    /**
     ********************************************************
     * @Method Name    : getMappingsByUniqueIdentifiers
     * @description    : Returns list of LOA Mappings by UniqueIdentifier (External ID)
     *                   UniqueIdentifier format: State-Code-Description
     * @param          : keys - Set of unique identifier values
     * @return         : List<ht_LOA_Insurance_Product_Mapping__c> - list of LOA Mapping records
     *******************************************************
     **/
    public List<ht_LOA_Insurance_Product_Mapping__c> getMappingsByUniqueIdentifiers(Set<String> keys) {
        return [
            SELECT
                Id,
                ht_StateOrProvinceCode__c,
                ht_LineOfAuthorityCode__c,
                ht_LineOfAuthorityDescription__c,
                ht_UniqueIdentifier__c
            FROM
                ht_LOA_Insurance_Product_Mapping__c
            WHERE
                ht_UniqueIdentifier__c IN :keys
        ];
    }

    /**
     ********************************************************
     * @Method Name    : getProductLOAJunctionsByLoaMappingIds
     * @description    : Returns list of Insurance Product LOA Mapping junction records by parent LOA Mapping IDs
     * @param          : mappingIds - Set of ht_LOA_Insurance_Product_Mapping__c IDs
     * @return         : List<ht_Insurance_Product_LOA_Mapping__c> - list of junction records
     *******************************************************
     **/
    public List<ht_Insurance_Product_LOA_Mapping__c> getProductLOAJunctionsByLoaMappingIds(Set<Id> mappingIds) {
        return [
            SELECT
                Id
            FROM
                ht_Insurance_Product_LOA_Mapping__c
            WHERE
                ht_LOAMapping__c IN :mappingIds
        ];
    }
}