force-app/main/default/objects/ht_Insurance_Product__c/fields/ht_ProductName__c.field-meta.xml
<CustomField>
    <fullName>ht_ProductName__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ht_Insurance_Product__c/fields/ht_StateOrProvince__c.field-meta.xml
<CustomField>
    <fullName>ht_StateOrProvince__c</fullName>
    <label>State Or Province</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ht_Insurance_Product_LOA_Mapping__c/ht_Insurance_Product_LOA_Mapping__c.object-meta.xml
<CustomObject>
    <label>NIPR Insurance Product LOA Mapping</label>
    <nameField>
        <displayFormat>IPLM-{0000}</displayFormat>
        <label>Mapping Product Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Insurance Product LOA Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ht_Insurance_Product_LOA_Mapping__c/fields/ht_InsuranceProduct__c.field-meta.xml
<CustomField>
    <fullName>d4c_InsuranceProduct__c</fullName>
    <label>Insurance Product</label>
    <referenceTo>d4c_Insurance_Product__c</referenceTo>
    <relationshipLabel>Insurance Product LOA Mappings</relationshipLabel>
    <relationshipName>Insurance_Product_LOA_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ht_Insurance_Product_LOA_Mapping__c/fields/ht_LOAMapping__c.field-meta.xml
<CustomField>
    <fullName>ht_LOAMapping__c</fullName>
    <label>LOA Mapping</label>
    <referenceTo>ht_LOA_Insurance_Product_Mapping__c</referenceTo>
    <relationshipLabel>LOA Mapping Insurance Products</relationshipLabel>
    <relationshipName>LOA_Mapping_Insurance_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ht_License__c/fields/ht_StateOrProvinceCode__c.field-meta.xml
<CustomField>
    <fullName>ht_StateOrProvinceCode__c</fullName>
    <label>State Or Province Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ht_License__c/fields/ht_UniqueIdentifier__c.field-meta.xml
<CustomField>
    <fullName>d4c_UniqueIdentifier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ht_License_Insurance_Product__c/fields/ht_InsuranceProduct__c.field-meta.xml
<CustomField>
    <fullName>d4c_InsuranceProduct__c</fullName>
    <label>Insurance Product</label>
    <referenceTo>d4c_Insurance_Product__c</referenceTo>
    <relationshipName>Insurance_Product_Licenses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ht_License_Insurance_Product__c/fields/ht_License__c.field-meta.xml
<CustomField>
    <fullName>ht_License__c</fullName>
    <label>License</label>
    <referenceTo>ht_License__c</referenceTo>
    <relationshipName>License_Insurance_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ht_LOA_Insurance_Product_Mapping__c/fields/ht_LineOfAuthorityCode__c.field-meta.xml
<CustomField>
    <fullName>ht_LineOfAuthorityCode__c</fullName>
    <label>Line Of Authority Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ht_LOA_Insurance_Product_Mapping__c/fields/ht_StateOrProvinceCode__c.field-meta.xml
<CustomField>
    <fullName>d4c_StateOrProvinceCode__c</fullName>
    <label>State Or Province Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ht_LOA_Insurance_Product_Mapping__c/fields/ht_UniqueIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ht_UniqueIdentifier__c</fullName>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Service/UniqueIdentifierService.cls
/*
*********************************************************
Apex Class Name    : UniqueIdentifierService
Created Date       : 2025-12-15
@description       : Service class for generating unique identifiers on LOA Product Categorization objects.
                     Centralizes unique identifier generation logic for:
                     - ht_Insurance_Product__c
                     - ht_LOA_Insurance_Product_Mapping__c
                     - ht_Insurance_Product_LOA_Mapping__c (junction)
                     - ht_License_Insurance_Product__c (junction)
@author            : Stefan Nidzovic
Modification Log:
Ver   Date         Author         Modification
1.0   2025-12-15   Stefan Nidzovic         Initial Version
*********************************************************
*/
public with sharing class UniqueIdentifierService {

    /**
     *********************************************************
     * @Method Name    : populateInsuranceProductUniqueId
     * @description    : Populates UniqueIdentifier for Insurance Product records.
     *                   Format: {StateOrProvince}-{ProductName}
     *                   Example: CA-Health Insurance
     * @param          : products - List of Insurance Product records to process
     *********************************************************
     */
    public void populateInsuranceProductUniqueId(List<ht_Insurance_Product__c> products) {
        for (ht_Insurance_Product__c product : products) {
            if (String.isNotBlank(product.ht_StateOrProvince__c) &&
                String.isNotBlank(product.ht_ProductName__c)) {
                product.ht_UniqueIdentifier__c = product.ht_StateOrProvince__c + '-' +
                    product.ht_ProductName__c;
            }
        }
    }

    /**
     *********************************************************
     * @Method Name    : populateLOAMappingUniqueId
     * @description    : Populates UniqueIdentifier for LOA Insurance Product Mapping records.
     *                   Format: {StateOrProvinceCode}-{LineOfAuthorityCode}-{LineOfAuthorityDescription}
     *                   Example: CA-935-Accident & Health
     * @param          : mappings - List of LOA Mapping records to process
     *********************************************************
     */
    public void populateLOAMappingUniqueId(List<ht_LOA_Insurance_Product_Mapping__c> mappings) {
        for (ht_LOA_Insurance_Product_Mapping__c mapping : mappings) {
            if (String.isNotBlank(mapping.ht_StateOrProvinceCode__c) &&
                String.isNotBlank(mapping.ht_LineOfAuthorityCode__c) &&
                String.isNotBlank(mapping.ht_LineOfAuthorityDescription__c)) {
                mapping.ht_UniqueIdentifier__c = mapping.ht_StateOrProvinceCode__c + '-' +
                    mapping.ht_LineOfAuthorityCode__c + '-' +
                    mapping.ht_LineOfAuthorityDescription__c;
            }
        }
    }

    /**
     *********************************************************
     * @Method Name    : populateInsProdLOAMappingUniqueId
     * @description    : Populates UniqueIdentifier for Insurance Product LOA Mapping junction records.
     *                   Format: {InsuranceProductId}-{LOAMappingId}
     * @param          : junctions - List of junction records to process
     *********************************************************
     */
    public void populateInsProdLOAMappingUniqueId(List<ht_Insurance_Product_LOA_Mapping__c> junctions) {
        for (ht_Insurance_Product_LOA_Mapping__c junction : junctions) {
            if (junction.ht_InsuranceProduct__c != null && junction.ht_LOAMapping__c != null) {
                junction.ht_UniqueIdentifier__c = String.valueOf(junction.ht_InsuranceProduct__c) +
                    '-' + String.valueOf(junction.ht_LOAMapping__c);
            }
        }
    }

    /**
     *********************************************************
     * @Method Name    : populateLicenseInsProdUniqueId
     * @description    : Populates UniqueIdentifier for License Insurance Product junction records.
     *                   Format: {LicenseId}-{InsuranceProductId}
     * @param          : junctions - List of junction records to process
     *********************************************************
     */
    public void populateLicenseInsProdUniqueId(List<ht_License_Insurance_Product__c> junctions) {
        for (ht_License_Insurance_Product__c junction : junctions) {
            if (junction.ht_License__c != null && junction.ht_InsuranceProduct__c != null) {
                junction.ht_UniqueIdentifier__c = String.valueOf(junction.ht_License__c) +
                    '-' + String.valueOf(junction.ht_InsuranceProduct__c);
            }
        }
    }
}