force-app/main/default/objects/ht_Insurance_Product__c/fields/ht_ProductName__c.field-meta.xml
<CustomField>
    <fullName>ht_ProductName__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ht_Insurance_Product__c/fields/ht_StateOrProvince__c.field-meta.xml
<CustomField>
    <fullName>ht_StateOrProvince__c</fullName>
    <label>State Or Province</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Repository/InsuranceProductSelector.cls
/*
*********************************************************
Apex Class Name    : InsuranceProductSelector
Created Date       : 2025-12-15
@description       : Selector class for querying ht_Insurance_Product__c records
@author            : Stefan Nidzovic
Modification Log:
Ver   Date         Author         Modification
1.0   2025-12-15   Stefan Nidzovic         Initial Version
*********************************************************
*/
public with sharing class InsuranceProductSelector {

    /**
     ********************************************************
     * @Method Name    : getProductsByIds
     * @description    : Returns list of Insurance Products by Id
     * @param          : productIds - Set of Insurance Product IDs
     * @return         : List<ht_Insurance_Product__c> - list of Insurance Product records
     *******************************************************
     **/
    public List<ht_Insurance_Product__c> getProductsByIds(Set<Id> productIds) {
        return [
            SELECT
                Id,
                ht_ProductName__c,
                ht_StateOrProvince__c,
                ht_UniqueIdentifier__c
            FROM
                ht_Insurance_Product__c
            WHERE
                Id IN :productIds
        ];
    }
}