force-app/main/default/objects/d4c_Entity__c/d4c_Entity__c.object-meta.xml
<CustomObject>
    <label>NIPR Entity</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Entity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_License__c/d4c_License__c.object-meta.xml
<CustomObject>
    <label>NIPR License</label>
    <nameField>
        <displayFormat>LIC-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_License__c/fields/d4c_Entity__c.field-meta.xml
<CustomField>
    <fullName>d4c_Entity__c</fullName>
    <label>Producer</label>
    <referenceTo>d4c_Entity__c</referenceTo>
    <relationshipName>Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/d4c_License__c/fields/d4c_License_Products__c.field-meta.xml
<CustomField>
    <fullName>d4c_License_Products__c</fullName>
    <label>License Products</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/d4c_License__c/fields/d4c_LicenseNumber__c.field-meta.xml
<CustomField>
    <fullName>d4c_LicenseNumber__c</fullName>
    <label>License Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/d4c_License__c/fields/d4c_StateOrProvinceCode__c.field-meta.xml
<CustomField>
    <fullName>d4c_StateOrProvinceCode__c</fullName>
    <label>State Or Province Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Repository/LicenseSelector.cls
/**
 *********************************************************
 * Apex Class Name    : LicenseSelector
 * Created Date       : 03-30-2025
 * @description       : Selector class holding all the queries used for d4c_License__c object
 * @author            : Stefan Nidzovic
 * Modification Log:
 * Ver   Date         Author                   Modification
 * 1.0   03-30-2025   Stefan Nidzovic          Initial Version
 *********************************************************
 **/
public with sharing class LicenseSelector {
    /**
     ********************************************************
     * @Method Name    : getCarrierAppointmentsByProducerNpn
     * @description    : Returns list of d4c_License__c by d4c_NPN__c of d4c_Entity__c object field
     * @param          : npns - Set of unique NPN values
     * @return         : List<d4c_License__c> - list of Producer records
     *******************************************************
     **/
    public List<d4c_License__c> getLicensesByProducerNpn(Set<String> npns) {
        return [
            SELECT
                Id,
                d4c_uniqueIdentifier__c,
                d4c_LicenseNumber__c,
                d4c_Entity__r.d4c_NPN__c
            FROM
                d4c_License__c
            WHERE
                d4c_Entity__r.d4c_NPN__c IN :npns
        ];
    }

    /**
     ********************************************************
     * @Method Name    : getLicensesByProducerNpnAndStates
     * @description    : Returns list of d4c_License__c by d4c_NPN__c and d4c_StateOrProvinceCode__c
     *                   Used for deletion logic to only query licenses for producer+state combinations
     *                   that have data in the NIPR payload
     * @param          : npns - Set of unique NPN values
     * @param          : states - Set of state/province codes
     * @return         : List<d4c_License__c> - list of License records
     *******************************************************
     **/
    public List<d4c_License__c> getLicensesByProducerNpnAndStates(Set<String> npns, Set<String> states) {
        return [
            SELECT
                Id,
                d4c_uniqueIdentifier__c,
                d4c_LicenseNumber__c,
                d4c_Entity__r.d4c_NPN__c,
                d4c_StateOrProvinceCode__c
            FROM
                d4c_License__c
            WHERE
                d4c_Entity__r.d4c_NPN__c IN :npns
                AND d4c_StateOrProvinceCode__c IN :states
        ];
    }

    /**
     ********************************************************
     * @Method Name    : getLicensesWithProductsFieldByIds
     * @description    : Returns list of Licenses with d4c_License_Products__c field by IDs
     *                   Used for updating the multi-select picklist of product names
     * @param          : licenseIds - Set of License IDs
     * @return         : List<d4c_License__c> - list of License records
     *******************************************************
     **/
    public List<d4c_License__c> getLicensesWithProductsFieldByIds(Set<Id> licenseIds) {
        return [
            SELECT
                Id,
                d4c_License_Products__c
            FROM
                d4c_License__c
            WHERE
                Id IN :licenseIds
        ];
    }
}