force-app/main/default/objects/d4c_Entity__c/d4c_Entity__c.object-meta.xml
<CustomObject>
    <label>NIPR Entity</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Entity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_Entity__c/fields/d4c_ExcludeCarrierAppointments__c.field-meta.xml
<CustomField>
    <fullName>d4c_ExcludeCarrierAppointments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, carrier appointments will be excluded from NIPR sync and this entity will be added to subscriptions that exclude carrier appointments. Can be set automatically for large payloads or manually by users.</description>
    <label>Exclude Carrier Appointments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/d4c_Entity__c/fields/d4c_Subscription__c.field-meta.xml
<CustomField>
    <fullName>d4c_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>d4c_Subscription__c</referenceTo>
    <relationshipName>Entitys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/d4c_Subscription__c/d4c_Subscription__c.object-meta.xml
<CustomObject>
    <label>NIPR Subscription</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_Subscription__c/fields/d4c_ExcludeCarrierAppointments__c.field-meta.xml
<CustomField>
    <fullName>d4c_ExcludeCarrierAppointments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this subscription excludes carrier appointments. Subscriptions with this flag set to true will only receive licensing alerts from NIPR and will only contain entitys with the Exclude Carrier Appointments flag enabled.</description>
    <label>Exclude Carrier Appointments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Repository/EntitySelector.cls
/*
*********************************************************
Apex Class Name    : EntitySelector
Created Date       : 2025-03-28
@description       : Selector class for querying d4c_Entity__c records
@author            : Dev4Clouds
Modification Log:
Ver   Date         Author          Modification
1.0   2025-03-28   Dev4Clouds   Initial Version
1.1   2025-03-31   Dev4Clouds   Modified to return List instead of Map, remove business logic from selector
1.2   2025-10-24   Dev4Clouds Added d4c_ExcludeCarrierAppointments__c field to queries
*********************************************************
*/
public with sharing class EntitySelector {

    /*********************************************************
     @Method Name    : getEntitiesByNPNs
     @description    : Returns list of d4c_Entity__c by d4c_NPN__c field
     @author         : Dev4Clouds
     @param          : npns - Set of unique NPN values
     @return         : List<d4c_Entity__c> - list of Entity records
     *********************************************************
    **/
    public List<d4c_Entity__c> getEntitiesByNPNs(Set<String> npns) {
        return [
            SELECT
                Id,
                d4c_NPN__c,
                d4c_NPNStatus__c,
                d4c_Subscription__c,
                d4c_ExcludeCarrierAppointments__c
            FROM 
                d4c_Entity__c
            WHERE 
                d4c_NPN__c IN :npns
        ];
    }
}