force-app/main/default/objects/d4c_Entity__c/d4c_Entity__c.object-meta.xml
<CustomObject>
    <label>NIPR Entity</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Entity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_Entity__c/fields/d4c_ExcludeCarrierAppointments__c.field-meta.xml
<CustomField>
    <fullName>d4c_ExcludeCarrierAppointments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, carrier appointments will be excluded from NIPR sync and this entity will be added to subscriptions that exclude carrier appointments. Can be set automatically for large payloads or manually by users.</description>
    <label>Exclude Carrier Appointments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/d4c_Entity__c/fields/d4c_Subscription__c.field-meta.xml
<CustomField>
    <fullName>d4c_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>d4c_Subscription__c</referenceTo>
    <relationshipName>Entitys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/d4c_Subscription__c/d4c_Subscription__c.object-meta.xml
<CustomObject>
    <label>NIPR Subscription</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_Subscription__c/fields/d4c_ExcludeCarrierAppointments__c.field-meta.xml
<CustomField>
    <fullName>d4c_ExcludeCarrierAppointments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this subscription excludes carrier appointments. Subscriptions with this flag set to true will only receive licensing alerts from NIPR and will only contain entitys with the Exclude Carrier Appointments flag enabled.</description>
    <label>Exclude Carrier Appointments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Repository/SubscriptionSelector.cls
/**
 *********************************************************
 * Apex Class Name    : SubscriptionSelector
 * Created Date       : 04-23-2025
 * @description       : Selector class holding all the queries used for d4c_Subscription__c and related objects
 * @author            : Dev4Clouds
 * Modification Log:
 * Ver   Date         Author                   Modification
 * 1.0   04-23-2025   Dev4Clouds          Initial Version
 * 1.1   10-24-2025   Dev4Clouds          Added methods for subscription refactoring
 *********************************************************
 **/
public with sharing class SubscriptionSelector {     

    /**
     ********************************************************
     * @Method Name    : getSubscriptionById
     * @description    : Returns a subscription record by its Id
     * @param          : subscriptionId - Id of the subscription record
     * @return         : d4c_Subscription__c - Subscription record
     *******************************************************
     **/
    public d4c_Subscription__c getSubscriptionById(Id subscriptionId) {
        return [
            SELECT
                Id,
                Name,
                d4c_Subscription_Name__c
            FROM
                d4c_Subscription__c
            WHERE
                Id = :subscriptionId
        ];
    }

    /**
     ********************************************************
     * @Method Name    : getSubscriptionsByIds
     * @description    : Returns subscription records by their ids
     * @param          : subscriptionIds - Ids of the subscription records
     * @return         : List<d4c_Subscription__c> - Subscription records
     *******************************************************
     **/
    public List<d4c_Subscription__c> getSubscriptionsByIds(Set<Id> subscriptionIds) {
        return [
            SELECT
                Id,
                Name,
                d4c_Subscription_Name__c
            FROM
                d4c_Subscription__c
            WHERE
                Id IN :subscriptionIds
        ];
    }

    /**
     ********************************************************
     * @Method Name    : getSubscriptionsWithEntitysByExcludeFlag
     * @description    : Returns subscriptions filtered by exclude carrier appointments flag with producer count
     * @param          : excludeCarrierAppointments - Boolean flag to filter subscriptions
     * @return         : List<d4c_Subscription__c> - List of subscription records with related producers
     *******************************************************
     **/
    public List<d4c_Subscription__c> getSubscriptionsWithEntitysByExcludeFlag(Boolean excludeCarrierAppointments) {
        return [
            SELECT Id, Name, d4c_Subscription_Name__c, d4c_ExcludeCarrierAppointments__c,
                (SELECT Id FROM Entitys__r)
            FROM d4c_Subscription__c
            WHERE d4c_ExcludeCarrierAppointments__c = :excludeCarrierAppointments
            ORDER BY CreatedDate ASC
        ];
    }

    /**
     ********************************************************
     * @Method Name    : getLatestSubscriptionByName
     * @description    : Returns the latest subscription ordered by Name (autonumber) descending
     * @return         : d4c_Subscription__c - Latest subscription record, or null if none exist
     *******************************************************
     **/
    public d4c_Subscription__c getLatestSubscriptionByName() {
        List<d4c_Subscription__c> latestSubs = [
            SELECT Id, Name, d4c_Subscription_Name__c
            FROM d4c_Subscription__c
            ORDER BY d4c_Subscription_Name__c DESC
            LIMIT 1
        ];

        return latestSubs.isEmpty() ? null : latestSubs[0];
    }
}