force-app/main/default/objects/d4c_Entity__c/d4c_Entity__c.object-meta.xml
<CustomObject>
    <label>NIPR Entity</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Entity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_Entity_Communication_Junction__c/d4c_Entity_Communication_Junction__c.object-meta.xml
<CustomObject>
    <label>Entity Communication</label>
    <pluralLabel>Entity Communications</pluralLabel>
    <nameField>
        <displayFormat>EC-{0000000}</displayFormat>
        <label>Entity Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_Entity_Communication_Junction__c/fields/d4c_Entity__c.field-meta.xml
<CustomField>
    <fullName>d4c_Entity__c</fullName>
    <label>Entity</label>
    <referenceTo>d4c_Entity__c</referenceTo>
    <relationshipName>Entity_Communication_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/d4c_Entity_Communication_Junction__c/fields/d4c_NIPR_Communication__c.field-meta.xml
<CustomField>
    <fullName>d4c_NIPR_Communication__c</fullName>
    <label>NIPR Communication</label>
    <referenceTo>d4c_NIPR_Communication__c</referenceTo>
    <relationshipName>Entity_Communication_Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/d4c_NIPR_Communication__c/d4c_NIPR_Communication__c.object-meta.xml
<CustomObject>
    <label>NIPR Communication</label>
    <nameField>
        <displayFormat>PRC-{0000}</displayFormat>
        <label>Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_NIPR_Communication__c/fields/d4c_Entity__c.field-meta.xml
<CustomField>
    <fullName>d4c_Entity__c</fullName>
    <label>Entity</label>
    <referenceTo>d4c_Entity__c</referenceTo>
    <relationshipName>Entity_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TriggerHandler/EntityCommunicationJunctionTriggerHandler.cls
/**
 *********************************************************
 * Apex Class Name    : EntityCommunicationJunctionTriggerHandler
 * Created Date       : 02-10-2026
 * @description       : Trigger handler for d4c_Entity_Communication_Junction__c
 *                      Populates unique identifier as combination of Entity ID + Communication ID
 * @author            : Dev4Clouds
 * Modification Log:
 * Ver   Date         Author                   Modification
 * 1.0   02-10-2026   Dev4Clouds          Initial Version
 *********************************************************
 **/
public with sharing class EntityCommunicationJunctionTriggerHandler extends BaseTriggerHandler {
    /**
     ********************************************************
     * @Method Name    : beforeInsert
     * @description    : Populates unique identifier before insert
     * @param          : newRecords - List of new junction records
     *******************************************************
     **/
    public override void beforeInsert(List<SObject> newRecords) {
        populateUniqueIdentifier((List<d4c_Entity_Communication_Junction__c>) newRecords);
    }

    /**
     ********************************************************
     * @Method Name    : beforeUpdate
     * @description    : Populates unique identifier before update
     * @param          : newRecords - List of updated junction records
     * @param          : oldRecords - List of old junction records
     *******************************************************
     **/
    public override void beforeUpdate(List<SObject> newRecords, List<SObject> oldRecords) {
        populateUniqueIdentifier((List<d4c_Entity_Communication_Junction__c>) newRecords);
    }

    /**
     ********************************************************
     * @Method Name    : populateUniqueIdentifier
     * @description    : Creates unique identifier from Entity ID + Communication ID
     * @param          : junctions - List of junction records
     *******************************************************
     **/
    private void populateUniqueIdentifier(List<d4c_Entity_Communication_Junction__c> junctions) {
        for (d4c_Entity_Communication_Junction__c junction : junctions) {
            if (junction.d4c_Entity__c != null && junction.d4c_NIPR_Communication__c != null) {
                junction.d4c_UniqueIdentifier__c = String.valueOf(junction.d4c_Entity__c) + '-' + String.valueOf(junction.d4c_NIPR_Communication__c);
            }
        }
    }
}