force-app/main/default/objects/ht_License__c/fields/ht_UniqueIdentifier__c.field-meta.xml
<CustomField>
    <fullName>d4c_UniqueIdentifier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ht_License_Insurance_Product__c/fields/ht_InsuranceProduct__c.field-meta.xml
<CustomField>
    <fullName>d4c_InsuranceProduct__c</fullName>
    <label>Insurance Product</label>
    <referenceTo>d4c_Insurance_Product__c</referenceTo>
    <relationshipName>Insurance_Product_Licenses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ht_License_Insurance_Product__c/fields/ht_License__c.field-meta.xml
<CustomField>
    <fullName>ht_License__c</fullName>
    <label>License</label>
    <referenceTo>ht_License__c</referenceTo>
    <relationshipName>License_Insurance_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Repository/LicenseInsuranceProductSelector.cls
/*
*********************************************************
Apex Class Name    : LicenseInsuranceProductSelector
Created Date       : 2025-12-15
@description       : Selector class for querying ht_License_Insurance_Product__c junction records
@author            : Stefan Nidzovic
Modification Log:
Ver   Date         Author         Modification
1.0   2025-12-15   Stefan Nidzovic         Initial Version
*********************************************************
*/
public with sharing class LicenseInsuranceProductSelector {

    /**
     ********************************************************
     * @Method Name    : getJunctionsByUniqueIdentifiers
     * @description    : Returns list of junctions by UniqueIdentifier (External ID)
     *                   UniqueIdentifier format: LicenseId-ProductId
     * @param          : identifiers - Set of unique identifier values
     * @return         : List<ht_License_Insurance_Product__c> - list of junction records
     *******************************************************
     **/
    public List<ht_License_Insurance_Product__c> getJunctionsByUniqueIdentifiers(Set<String> identifiers) {
        return [
            SELECT
                Id,
                ht_License__c,
                ht_InsuranceProduct__c,
                ht_UniqueIdentifier__c
            FROM
                ht_License_Insurance_Product__c
            WHERE
                ht_UniqueIdentifier__c IN :identifiers
        ];
    }
}