force-app/main/default/objects/ht_Logger__c/ht_Logger__c.object-meta.xml
<CustomObject>
    <label>NIPR Logger</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ht_Logger__c/fields/ht_Details__c.field-meta.xml
<CustomField>
    <fullName>ht_Details__c</fullName>
    <inlineHelpText>Captures the actual error message or log details.</inlineHelpText>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ht_Logger__c/fields/ht_LogLevel__c.field-meta.xml
<CustomField>
    <fullName>d4c_LogLevel__c</fullName>
    <inlineHelpText>Defines the severity of the log: Info, Debug, Warning, Error.</inlineHelpText>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ht_Logger__c/fields/ht_Message__c.field-meta.xml
<CustomField>
    <fullName>d4c_Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test/DeleteLogsBatchableTest.cls
/**
 * @description       : 
 * @author            : Stefan Nidzovic
 * @group             : 
 * @last modified on  : 04-30-2025
 * @last modified by  : Stefan Nidzovic
**/
@isTest
public class DeleteLogsBatchableTest {
    
    @testSetup
    static void setupTestData() {
        // Insert test ht_Logger__c records
        List<ht_Logger__c> logRecords = new List<ht_Logger__c>();
        for (Integer i = 0; i < 10; i++) {
            ht_Logger__c log = new ht_Logger__c();

            log.ht_LogLevel__c = 'Info';
            log.ht_Message__c = 'Test Message ' + i;
            log.ht_Details__c = 'Test Details ' + i;

            logRecords.add(log);
        }

        insert logRecords;

        for (Integer i = 0; i < 10; i++) {
            if (Math.mod(i, 2) == 0) {
                Test.setCreatedDate(logRecords[i].Id, Datetime.now().addDays(-14));
            }
        }

        update logRecords;
    }

    @isTest
    static void testDeleteLogsBatch() {
        // create data
        Integer initialCount = [SELECT COUNT() FROM ht_Logger__c];
        System.assertEquals(10, initialCount, 'Initial count of ht_Logger__c records should be 10');

        // execute
        Test.startTest();
        new DeleteLogsScheduleable().execute(null);
        Test.stopTest();

        // assert
        Integer finalCount = [SELECT COUNT() FROM ht_Logger__c];
        System.assertEquals(5, finalCount, 'All ht_Logger__c records should be deleted');
    }

    @isTest
    static void testScheduleMethod() {
        Id jobId = DeleteLogsScheduleable.scheduleTwiceMonthly();

        System.assert(jobId == null);
    }
}