force-app/main/default/objects/d4c_License__c/d4c_License__c.object-meta.xml
<CustomObject>
    <label>NIPR License</label>
    <nameField>
        <displayFormat>LIC-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_License__c/fields/d4c_LicenseNumber__c.field-meta.xml
<CustomField>
    <fullName>d4c_LicenseNumber__c</fullName>
    <label>License Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/d4c_LineOfAuthority__c/d4c_LineOfAuthority__c.object-meta.xml
<CustomObject>
    <label>NIPR Line Of Authority</label>
    <nameField>
        <displayFormat>LOA-{0000}</displayFormat>
        <label>Line Of Authority Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Lines Of Authority</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/d4c_LineOfAuthority__c/fields/d4c_License__c.field-meta.xml
<CustomField>
    <fullName>d4c_License__c</fullName>
    <label>License</label>
    <referenceTo>d4c_License__c</referenceTo>
    <relationshipLabel>NIPR Lines Of Authority</relationshipLabel>
    <relationshipName>Lines_Of_Authority</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Repository/LineOfAuthoritySelector.cls
/*
*********************************************************
Apex Class Name    : LineOfAuthoritySelector
Created Date       : 2025-04-09
@description       : Selector class for querying d4c_LineOfAuthority__c records
@author            : Dev4Clouds
Modification Log:
Ver   Date         Author         Modification
1.0   2025-04-09   Dev4Clouds  Initial Version
*********************************************************
*/
public virtual class LineOfAuthoritySelector {
    /**
     ********************************************************
     * @Method Name    : getLOAByLicenseNumber
     * @description    : Returns list of d4c_LineOfAuthority__c by d4c_UniqueIdentifier__c field of d4c_License__c object
     * @param          : licenseUniqueIdentifiers - Set of unique license identifiers values
     * @return         : List<d4c_LineOfAuthority__c> - list of LOA records
     *******************************************************
     **/
    public List<d4c_LineOfAuthority__c> getLOAByUniqueIdentifier(Set<String> licenseUniqueIdentifiers) {
        return [
            SELECT
                Id,
                d4c_UniqueIdentifier__c,
                d4c_License__r.d4c_LicenseNumber__c,
                d4c_License__r.d4c_UniqueIdentifier__c
            FROM
                d4c_LineOfAuthority__c
            WHERE
                d4c_License__r.d4c_UniqueIdentifier__c IN :licenseUniqueIdentifiers
        ];
    }

}