force-app/main/default/objects/ht_Producer__c/ht_Producer__c.object-meta.xml
<CustomObject>
    <label>NIPR Producer</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Producer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Producers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ht_Producer__c/fields/ht_NPN__c.field-meta.xml
<CustomField>
    <fullName>d4c_NPN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>NPN</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ht_ProducerCommunication__c/ht_ProducerCommunication__c.object-meta.xml
<CustomObject>
    <label>NIPR Producer Communication</label>
    <nameField>
        <displayFormat>PRC-{0000}</displayFormat>
        <label>Producer Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Producer Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ht_ProducerCommunication__c/fields/ht_EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>ht_EmailAddress__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ht_ProducerCommunication__c/fields/ht_EmailType__c.field-meta.xml
<CustomField>
    <fullName>d4c_EmailType__c</fullName>
    <label>Email Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ht_ProducerCommunication__c/fields/ht_PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>ht_PhoneNumber__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ht_ProducerCommunication__c/fields/ht_PhoneType__c.field-meta.xml
<CustomField>
    <fullName>ht_PhoneType__c</fullName>
    <label>Phone Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ht_ProducerCommunication__c/fields/ht_Producer__c.field-meta.xml
<CustomField>
    <fullName>ht_Producer__c</fullName>
    <label>Producer</label>
    <referenceTo>ht_Producer__c</referenceTo>
    <relationshipName>Producer_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Repository/ProducerCommunicationSelector.cls
/**
 *********************************************************
 * Apex Class Name    : ProducerCommunicationSelector
 * Created Date       : 03-30-2025
 * @description       : Selector class holding all the queries used for ht_ProducerCommunication__c object
 * @author            : Stefan Nidzovic
 * Modification Log:
 * Ver   Date         Author                   Modification
 * 1.0   03-30-2025   Stefan Nidzovic          Initial Version
 *********************************************************
 **/
public with sharing class ProducerCommunicationSelector {
    /**
     ********************************************************
     * @Method Name    : getProducerCommsByProducerNPNs
     * @description    : Returns list of ht_ProducerCommunication__c by ht_NPN__C field of ht_Producer__c object
     * @param          : npns - Set of unique NPN values
     * @return         : List<ht_ProducerCommunication__c> - list of Producer Communication records
     *******************************************************
     **/
    public List<ht_ProducerCommunication__c> getProducerCommsByProducerNPNs(Set<String> npns) {
        return [
            SELECT
                Id,
                ht_UniqueIdentifier__c,
                ht_PhoneType__c,
                ht_PhoneNumber__c,
                ht_EmailType__c,
                ht_EmailAddress__c,
                ht_Producer__r.ht_NPN__c
            FROM
                ht_ProducerCommunication__c
            WHERE
                ht_Producer__r.ht_NPN__c IN :npns
        ];
    }
}