force-app/main/default/objects/ht_Producer__c/ht_Producer__c.object-meta.xml
<CustomObject>
    <label>NIPR Producer</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Producer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Producers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ht_Producer__c/fields/ht_NPN__c.field-meta.xml
<CustomField>
    <fullName>d4c_NPN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>NPN</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ht_ProducerAddress__c/ht_ProducerAddress__c.object-meta.xml
<CustomObject>
    <label>NIPR Producer Address</label>
    <nameField>
        <displayFormat>PRA-{0000}</displayFormat>
        <label>Producer Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Producer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ht_ProducerAddress__c/fields/ht_Producer__c.field-meta.xml
<CustomField>
    <fullName>ht_Producer__c</fullName>
    <label>Producer</label>
    <referenceTo>ht_Producer__c</referenceTo>
    <relationshipName>Producer_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Repository/ProducerAddressSelector.cls
/**
 *********************************************************
 * Apex Class Name    : ProducerAddressSelector
 * Created Date       : 03-30-2025
 * @description       : Selector class holding all the queries used for ht_ProducerAddress__c object
 * @author            : Stefan Nidzovic
 * Modification Log:
 * Ver   Date         Author                   Modification
 * 1.0   03-30-2025   Stefan Nidzovic          Initial Version
 *********************************************************
 **/
public with sharing class ProducerAddressSelector {
    /**
     ********************************************************
     * @Method Name    : getProducerAddressByProducerNPNs
     * @description    : Returns list of ht_ProducerAddress__c by ht_NPN__C field of ht_Producer__c object
     * @param          : npns - Set of unique NPN values
     * @return         : List<ht_ProducerAddress__c> - list of Producer Address records
     *******************************************************
     **/
    public List<ht_ProducerAddress__c> getProducerAddressByProducerNPNs(Set<String> npns) {
        return [
            SELECT
                Id,
                ht_UniqueIdentifier__c,
                ht_Producer__r.ht_NPN__c
            FROM
                ht_ProducerAddress__c
            WHERE
                ht_Producer__r.ht_NPN__c IN :npns
        ];
    }
}