force-app/main/default/objects/ht_Producer__c/ht_Producer__c.object-meta.xml
<CustomObject>
    <label>NIPR Producer</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Producer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Producers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ht_Producer__c/fields/ht_ExcludeCarrierAppointments__c.field-meta.xml
<CustomField>
    <fullName>ht_ExcludeCarrierAppointments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, carrier appointments will be excluded from NIPR sync and this producer will be added to subscriptions that exclude carrier appointments. Can be set automatically for large payloads or manually by users.</description>
    <label>Exclude Carrier Appointments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ht_Producer__c/fields/ht_NPN__c.field-meta.xml
<CustomField>
    <fullName>d4c_NPN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>NPN</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ht_Producer__c/fields/ht_NPNStatus__c.field-meta.xml
<CustomField>
    <fullName>ht_NPNStatus__c</fullName>
    <label>NPN Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Invalid NPN</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sync Disabled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ht_Producer__c/fields/ht_Subscription__c.field-meta.xml
<CustomField>
    <fullName>ht_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>ht_Subscription__c</referenceTo>
    <relationshipName>Producers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ht_Subscription__c/ht_Subscription__c.object-meta.xml
<CustomObject>
    <label>NIPR Subscription</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIPR Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ht_Subscription__c/fields/ht_ExcludeCarrierAppointments__c.field-meta.xml
<CustomField>
    <fullName>d4c_ExcludeCarrierAppointments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this subscription excludes carrier appointments. Subscriptions with this flag set to true will only receive licensing alerts from NIPR and will only contain producers with the Exclude Carrier Appointments flag enabled.</description>
    <label>Exclude Carrier Appointments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Repository/ProducerSelector.cls
/*
*********************************************************
Apex Class Name    : ProducerSelector
Created Date       : 2025-03-28
@description       : Selector class for querying ht_Producer__c records
@author            : Uros Markovic
Modification Log:
Ver   Date         Author          Modification
1.0   2025-03-28   Uros Markovic   Initial Version
1.1   2025-03-31   Uros Markovic   Modified to return List instead of Map, remove business logic from selector
1.2   2025-10-24   Stefan Nidzovic Added ht_ExcludeCarrierAppointments__c field to queries
*********************************************************
*/
public with sharing class ProducerSelector {

    /*********************************************************
     @Method Name    : getProducersByNPNs
     @description    : Returns list of ht_Producer__c by ht_NPN__c field
     @author         : Uros Markovic
     @param          : npns - Set of unique NPN values
     @return         : List<ht_Producer__c> - list of Producer records
     *********************************************************
    **/
    public List<ht_Producer__c> getProducersByNPNs(Set<String> npns) {
        return [
            SELECT
                Id,
                ht_NPN__c,
                ht_NPNStatus__c,
                ht_Subscription__c,
                ht_ExcludeCarrierAppointments__c
            FROM 
                ht_Producer__c
            WHERE 
                ht_NPN__c IN :npns
        ];
    }
}